version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: memory_map-backend
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: memory_map-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
