version: '3.8'

services:
  backend:
    image: memory_map-backend  # Must match the loaded image name
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]

  frontend:
    image: memory_map-frontend  # Must match the loaded image name
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
